Default: &defaults
  database: yosogr.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: yosogr_test.sqlite3
  <<: *defaults

Staging:
  database: yosogr_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yosogr_production.sqlite3
  poolsize: 100
  <<: *defaults